#!/bin/bash

alias 0='/opt/BLEX/0.rb'
alias 1='/opt/BLEX/1.rb'
alias 2='/opt/BLEX/2.rb'
alias 3='/opt/BLEX/3.rb'
alias 4='/opt/BLEX/4.rb'
alias 5='/opt/BLEX/5.rb'

unalias 6 2>/dev/null
unalias 7 2>/dev/null
unalias 8 2>/dev/null
unalias 9 2>/dev/null
unalias 10 2>/dev/null
unalias 11 2>/dev/null
unalias 12 2>/dev/null
