#!/bin/bash

alias 0='/opt/REST/0.rb'
alias 1='/opt/REST/1.rb'
alias 2='/opt/REST/2.rb'
alias 3='/opt/REST/3.rb'
alias 4='/opt/REST/4.rb'

unalias 5 2>/dev/null
unalias 6 2>/dev/null
unalias 7 2>/dev/null
unalias 8 2>/dev/null
unalias 9 2>/dev/null
unalias 10 2>/dev/null
unalias 11 2>/dev/null
unalias 12 2>/dev/null
